--- ButtonTextureEnum.lua
--- Created by dreamness
--- DateTime: 2024/11/3 18:41
---

-- todo 补充和修改名字
--- @class ButtonTextureEnum
ButtonTextureEnum = {
    Button_AlliedCommandoTech1_on_02 = "Button_AlliedCommandoTech1_on_02",
    qilintank_EMP = "qilintank_EMP",
    Portrait_SovietHighTechStructure = "Portrait_SovietHighTechStructure",
    CelestialSpaceReinforce = "CelestialSpaceReinforce",
    Portrait_CelestialPowerPlant = "Portrait_CelestialPowerPlant",
    AUA_Mirage_GapGeneratorAUA_Mirage_StrikeMode = "AUA_Mirage_GapGeneratorAUA_Mirage_StrikeMode",
    Button_JapanRefinery = "Button_JapanRefinery",
    CelestialLightningTroop_Lv3 = "CelestialLightningTroop_Lv3",
    Portrait_AlliedBomberAircraftTrans = "Portrait_AlliedBomberAircraftTrans",
    AUA_Unpack = "AUA_Unpack",
    AlliedGunshipAircraftHyperSpaceMove = "AlliedGunshipAircraftHyperSpaceMove",
    Allied_topmenu_defense = "Allied_topmenu_defense",
    Portrait_SovietAntiNavyShipTech3_HeliTakeOff = "Portrait_SovietAntiNavyShipTech3_HeliTakeOff",
    JUA_TBuster_Burrow = "JUA_TBuster_Burrow",
    Portrait_CelestialMachineArm = "Portrait_CelestialMachineArm",
    Portrait_AlliedHeavyArtilleryDefenseBase = "Portrait_AlliedHeavyArtilleryDefenseBase",
    Button_PlayerPower_Telekenetic = "Button_PlayerPower_Telekenetic",
    CelestialSatelliteLaserSweep_Lv1 = "CelestialSatelliteLaserSweep_Lv1",
    JUA_KingOni_BullRush = "JUA_KingOni_BullRush",
    Button_JapanWarFactory_T3 = "Button_JapanWarFactory_T3",
    Button_CelestialAdvancedAircraftTech4 = "Button_CelestialAdvancedAircraftTech4",
    Button_CelestialEnergyRailgunBase = "Button_CelestialEnergyRailgunBase",
    Button_CelestialAntiStructureShip = "Button_CelestialAntiStructureShip",
    Button_AlliedBaseDefense_on = "Button_AlliedBaseDefense_on",
    Button_JapanKamikazeCommandTower = "Button_JapanKamikazeCommandTower",
    Button_CelestialAntiNavyShipTech2 = "Button_CelestialAntiNavyShipTech2",
    JapanAVVT4Heal = "JapanAVVT4Heal",
    SUA_Tank_LeechBeam = "SUA_Tank_LeechBeam",
    Portrait_CelestialBattery = "Portrait_CelestialBattery",
    Button_PlayerPower_AirPower = "Button_PlayerPower_AirPower",
    Button_PlayerPower_CryoSatellite2 = "Button_PlayerPower_CryoSatellite2",
    SUA_RocketLauncher_MultiWarhead = "SUA_RocketLauncher_MultiWarhead",
    Button_AlliedNavalYard_on = "Button_AlliedNavalYard_on",
    JUA_Shinobi_SmokeBomb = "JUA_Shinobi_SmokeBomb",
    Button_AlliedFighterAircraft_on = "Button_AlliedFighterAircraft_on",
    Button_AlliedWarFactory_on = "Button_AlliedWarFactory_on",
    CelestialNavalYardMissileTower = "CelestialNavalYardMissileTower",
    JUA_Cruiser_TorpedoS = "JUA_Cruiser_TorpedoS",
    Portrait_CelestialForkLiftVehicle = "Portrait_CelestialForkLiftVehicle",
    Button_CelestialAntiInfantryVehicle_B_Heavy = "Button_CelestialAntiInfantryVehicle_B_Heavy",
    Button_CelestialAntiVehicleVehicleTech4 = "Button_CelestialAntiVehicleVehicleTech4",
    AUA_Peacekeeper_Shield = "AUA_Peacekeeper_Shield",
}