-- TODO: test, package, feature
--- 创建自定义attrbuteModifier
--- @param type_value number 类型
--- @param stack_limit number 最大叠加层数
--- @return number 自定义attrbuteModifier id
function exAttributeModifierCreate(type_value, stack_limit) end
-- type 类型 整数
-- value 值
-- stackLimit 最大叠加层数
-- 类型有这些 (写后面的数字)
  --AttributeType_ARMOR = 1,
  --AttributeType_DAMAGE_ADD = 2,
  --AttributeType_DAMAGE_MULT = 3,
  --AttributeType_RESIST_FEAR = 4,
  --AttributeType_RESIST_TERROR = 5,
  --AttributeType_EXPERIENCE = 6,
  --AttributeType_RANGE = 7,
  --AttributeType_SPEED = 8,
  --AttributeType_CRUSH_DECELERATE = 9,
  --AttributeType_RESIST_KNOCKBACK = 10,
  --AttributeType_SPELL_DAMAGE = 11,
  --AttributeType_RECHARGE_TIME = 12,
  --AttributeType_PRODUCTION = 13,
  --AttributeType_PRODUCTION_COST = 14,
  --AttributeType_HEALTH = 15,
  --AttributeType_HEALTH_MULT = 16,
  --AttributeType_VISION = 17,
  --AttributeType_BOUNTY_PERCENTAGE = 18,
  --AttributeType_MIN_CRUSH_VELOCITY_PERCENTAGE = 19,
  --AttributeType_AUTO_HEAL = 20,
  --AttributeType_SHROUD_CLEARING = 21,
  --AttributeType_RATE_OF_FIRE = 22,
  --AttributeType_DAMAGE_STRUCTURE_BOUNTY_ADD = 23,
  --AttributeType_CRUSHER_LEVEL = 24,
  --AttributeType_COMMAND_POINT_BONUS = 25,
  --AttributeType_CRUSHABLE_LEVEL = 26,
  --AttributeType_CRUSHED_DECELERATE = 27,
  --AttributeType_INVULNERABLE = 28,
  --AttributeType_SUPPRESSABILITY = 29,
  --AttributeType_RESIST_EMP = 30,
  --AttributeType_POWER_BOOST = 31,
  --AttributeType_AREA_OF_EFFECT = 32,
  --AttributeType_COLLISION_GEOMETRY_SIZE_MULT = 33,
  --AttributeType_BROADCAST_RANGE = 34,

-- TODO: test, package, feature
-- 使用自定义attrbuteModifier
--- @param object_id number 物体id
--- @param attr_id number 自定义attrbuteModifier id
--- @param time number 持续时间
function exAttributeModifierUse(object_id, attr_id, time) end

